# -*- coding: utf-8 -*-
"""IntroToPython_778.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1idy3VwjZHmWDLfh2B0wXtMr6gX3QGYzm
"""

print("Hello World")

import os
cwd = os.getcwd()
print(cwd)

# variables and assignments
print("Hello") # Print Hello

my_var = 2
print(my_var)
my_var = "Saturday"
print(my_var)

class_day = "Saturday"
attendance = 11
print("Class is on", class_day, "and there are", attendance, "people in attendance")

x = 2
X = 5
print(x, X)

a, b, c = 5, "Hello", True
print(a,b,c)

string_var = 'Hello'
string_var2 = "Hello"
print(string_var, string_var2)

import urllib.request
from bs4 import BeautifulSoup

peak_page = "https://www.peakbagger.com/peak.aspx?pid=4157"
page = urllib.request.urlopen(peak_page)
print(page)

soup = BeautifulSoup(page, "html.parser")
find_elev = soup.find("h2")
find_name = soup.find("h1")

print(find_elev)
elev_value = find_elev.text.strip()
print(elev_value)

name_string = find_name.text.strip()

print(elev_value)
print(name_string)

string_list = elev_value.split() # seperate a string into a list of words based on spaces
print(string_list)
print(string_list[1])

string_list = elev_value.split(',')
print(string_list)

students = 11
print("This class has",students,"students in it.")

# using format characters to print
print("This class is on %s and has %d students in it" %("Saturdays", students))

a = 5+11**2/(3*5)
print(a)

reminder = 20 % 3 # modulo
print(reminder)

print(11**2%15)

print(type(a))
a = "hello"
print(type(a))

x = 5
print(x*10)
print(float(x)*10)

print(range(5))
for i in range(10):
  print(i, "Hello")

for x in [5,10,15,20]:
  print(x)

for x in "Hello":
  print(x)

#while loops
index = 0
while index < 10:
  print(index)
  index = index + 1

string_list = ["Monday", "Tuesday"]
for day in string_list:
  print(day)

# conditionals!
X = True
Y = False
if (X):
  print("X is True")
else:
  print("X is False")

x = int(input("Enter your favorite number:"))
if x < 10:
  print("Small")
elif x == 17:
  print("Exception")
elif x < 20:
  print("You're on your way...")
else:
  print("That's a good number")

# Functions
def getMean(x):
  return sum(x)/len(x)

x = [10, 15, 3, 4, 11, 15]
mean_x = getMean(x)
print(mean_x)

import math
def getSD(x):
  mean_x = getMean(x)
  eval_x = []
  for i in x:
    xi = (i - mean_x)**2
    eval_x.append(xi)
  z = math.sqrt(sum(eval_x)/len(eval_x))
  return z

print(getSD(x))

# List !!
test_list = [1, 2, 3, 4, 5]
print(test_list)
print(test_list[2])
test_list[2] = 10
print(test_list)

test_list1 = ["a", 5, 4.5, True]
print(test_list1)

test_list2 = ["b", 15]
test_list3 = test_list1 + test_list2
print(test_list3)

# creating list
x = []
y = list()
print(x, y)

# append
x.append("hello")
print(x)

y = [1, 2, 3, 4, 5]
print(len(y))
print(max(y))
print(min(y))
print(sum(y))
if 4 in y:
  print("Yes, 4 is in y")

if "hello" in x:
  print("Yes, hello is in x")
  
if "Hello" in x:
  print("Yes, Hello is in x")

# Tuples!

x  = (1, 2, 3, 4, 5)
print(x)
print(x[1])
print(x.index(4))
y = list(x)
print(y)
z = set(y)
print(z)

# Dictionaries
student_data = {}

student_data["Kelly"] = [90, 87, 42]
student_data["Carson"] = [56, 67, 76]
student_data["Morgan"] = [80, 83, 82]

student_data["Akshay"] = [80, 95, 99, 92]
student_data["Emily"] = {}
student_data["Emily"]["demographic"] = ["female", 30, "US"]
student_data["Emily"]["grades"] = [85, 42, 36]

print(student_data.keys())
print(sorted(student_data.keys()))
print(student_data["Kelly"])

for student in student_data:
  print(student, student_data[student])

for i, j in student_data.items():
  print(i, j)

# files
from google.colab import files
uploaded = files.upload()

NVData = open("NV_Cities.txt", r)
city_names = []
for line in NVData:
  line = line.strip()
  line = line.split()
  city_names.append(line[0])

print(city_names)
NVData.close()

fout = open("numbers.txt", 'w')

for i in range(10):
  fout.write(str(i)  + "\n")

fout.close()

fin = open("numbers.txt", 'r')
for line in fin:
  line = line.strip()
  print(line)
fin.close()

import os
os.listdir('.')

# numpy
import numpy as np
A = np.array([[1, 2], [3, 4]])
print(A)
B = np.array([[10, 20], [30, 40]])
print(B)

print(A+B)
print(A*B)
print(np.dot(A, B))

# plot!
import matplotlib.pyplot as plt

plt.plot([1, 2, 3, 4], [1, 4, 9, 16], 'ro') # specify the color and the plot marks
plt.xlabel("x")
plt.ylabel("y")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0, 5, 0.2)
print(t)
plt.plot(t, t**2, 'g-')
plt.plot(t, t**3, 'ro')
plt.title("t^2 and t^3 plot")
plt.show()

pip install census

from census import Census

# excel saves as csv files
import csv
csvfile = open("Others_Cities.csv", 'w', newline='')
csvwriter = csv.writer(csvfile, delimiter = ',')
csvwriter.writerow(["City", "x", "y", "Population"])
csvwriter.writerow(["Reno", -119.81, 39.51, 248853])
csvwriter.writerow(["Sparks", -119.75, 39.53, 100888])
csvfile.close()

csvfile = open("Others_Cities.csv", 'r')
csvreader = csv.reader(csvfile)
for line in csvreader:
  print(line)
csvfile.close()